### ISSUE TITLE
Game Error after installing the mod. v. 1.22 GoG

### ISSUE THREAD

**Issue by PrMinisterGR** [cvax/modPS4#2]
First of all, thanks for your idea and work! Unfortunately it doesn't seem to work in my case. The game crashes with the following error. I have no other controller mods installed. The mods I have installed are:
- Lowered hood Feline-1551-1-3
- STLM 2.2.1-657-2-2-1
- The Witcher 3 HD Reworked Project 3.31-1021-3-31

They work fine together. When I remove your mod the game starts normally.

> Error [content0]game\temp.ws(8702): Could not find function 'AddSessionTag'
> Error [content0]game\temp.ws(8707): Could not find function 'RemoveSessionTag'
> Error [content0]game\temp.ws(10731): Cannot call exec function 'XDPPrintUserStats' from scripts instead of the console.
> Error [content0]game\temp.ws(10736): Cannot call exec function 'XDPPrintUserAchievement' from scripts instead of the console.
> Error [content0]game\temp.ws(11134): Could not find function 'SetGameProgress'
> Error [content0]game\gameplay\alchemy\alchemymanager.ws(292): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\gameplay\alchemy\alchemymanager.ws(296): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\gameplay\leveling\levelmanager.ws(277): Could not find function 'LogWithValue'
> Error [content0]game\gameplay\leveling\levelmanager.ws(286): Could not find function 'LogWithValue'
> Error [content0]game\gameplay\leveling\levelmanager.ws(409): Could not find function 'LogWithValue'
> Error [content0]game\npc\npc.ws(1875): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\npc\npc.ws(2654): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\player\player.ws(1084): Could not find function 'LogWithLabel'
> Error [content0]game\player\r4player.ws(8339): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\player\r4player.ws(11159): Could not find function 'LogWithLabel'
> Error [content0]game\player\r4player.ws(13147): Could not find function 'LogWithLabel'
> Error [content0]game\player\playerwitcher.ws(5186): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\player\playerwitcher.ws(5561): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\player\playerwitcher.ws(6025): Could not find function 'LogWithValueStr'
> Error [content0]game\player\playerwitcher.ws(6424): Could not find function 'LogWithLabel'
> Error [content0]game\components\inventorycomponent.ws(181): Could not find function 'LogWithValue'
> Error [content0]game\components\inventorycomponent.ws(194): Could not find function 'LogWithValue'
> Error [content0]game\components\inventorycomponent.ws(739): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\components\inventorycomponent.ws(2202): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\r4game.ws(1658): Could not find function 'SetCommonStatI32'
> Error [content0]game\gameplay\focus\focus.ws(207): Could not find function 'LogWithName'
> Error [content0]game\gameplay\focus\focus.ws(267): Could not find function 'LogWithName'
> Error [modps4]game\gui\hud\hud.ws(1191): Could not find function 'LogWithLabel'
> Error [modps4]game\gui\hud\hud.ws(1192): Could not find function 'LogWithLabelAndValue'
> Error [modps4]game\gui\hud\hud.ws(1196): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\gui\menus\gwintgamemenu.ws(107): Could not find function 'LogWithName'
> Error [content0]game\gui\menus\gwintgamemenu.ws(123): Could not find function 'LogWithValue'
> Error [content0]game\gui\menus\gwintgamemenu.ws(128): Could not find function 'LogWithValue'
> Error [content0]game\gui\menus\inventorymenu.ws(2872): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\gui\menus\inventorymenu.ws(2945): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\gui\menus\craftingmenu.ws(265): Could not find function 'LogWithLabelAndValue'
> Error [content0]game\gameplay\ability\playerabilitymanager.ws(443): Could not find function 'SetCommonStatFlt'
> Error [content0]game\gameplay\ability\playerabilitymanager.ws(495): Could not find function 'SetCommonStatFlt'
> Error [content0]game\gameplay\ability\playerabilitymanager.ws(618): Could not find function 'LogWithValueStr'
> Error [content0]game\gameplay\ability\playerabilitymanager.ws(1602): Could not find function 'LogWithValueStr'
> Error [content0]game\player\states\vehicles\usevehicle.ws(1601): Could not find function 'LogWithValueStr'
> Error [content0]game\player\states\vehicles\horseriding.ws(49): Could not find function 'LogWithName'
> Error [content0]game\player\states\vehicles\sailing.ws(56): Could not find function 'LogWithName'
> Error [content0]game\player\states\playerdialogstate.ws(48): Could not find function 'LogWithName'
> Error [content0]game\player\states\aimthrow.ws(42): Could not find function 'LogWithName'
> Error [content0]game\player\states\combat.ws(124): Could not find function 'LogWithName'
> Error [content0]game\player\states\exploration.ws(55): Could not find function 'LogWithName'
> Error [content0]game\player\states\swimming.ws(252): Could not find function 'LogWithName'
> 
> Warning [content0]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
> Warning [content0]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
> Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.

**Comment by cvax** [comment]
Looks like erroneous Script Merges. You are running into a lot of errors on files this mod doesn't touch.
Be sure to also install vanilla CDPR scripts. You can find it in the files section of the [Custom Localization Fix](http://www.nexusmods.com/witcher3/mods/897/?) mod.
